GEOS-ESM/ESMA_cmake

- Externals.cfg
Move the External from tclune repo to GEOS-ESM
> Fixes #11. Point to GEOS-ESM ecbuild

- esma.cmake
- esma_check_if_debug.cmake
Use OPTION() for bool cmake options.
> Fixes #23.

- FindBaselibs.cmake
- esma.cmake
> updated to pfunit-4.0

- FindBaselibs.cmake
- esma.cmake
As the title says, this gets our bits of `develop` onto master for the 2.0 release.
> Merge develop onto master for 2.0 release

- CHANGELOG.md
- esma.cmake
- esma_check_python_module.cmake
- esma_find_python_module.cmake
- Added cmake macro esma_find_python_module() that detects whether
a given module is included in the Python distribution in use.
> Fixes #70 - check Python distribution

- CHANGELOG.md
- esma_add_library.cmake
- Added option is esma_add_library() to use SHARED
> Fixes #72 - enable shared libraries

- esma_add_subdirectories.cmake
- The "not found" branch should have been outside the loop.
(Maybe this should be to master)
> Patch for fix # 58.

- .gitignore
- esma.cmake
- allow ecbuild to be mounted as @ecbuild, ecbuild@ or just ecbuild.
> Fixes #87 - ecbuild@

- Externals.cfg
- esma_add_library.cmake
* Added ability to use ecbuild's NOINSTALL option.
* Update Externals.cfg for new ecbuild
> Updates for JEDI Integration

- CHANGELOG.md
Mainly to prevent Changelog conflicts
> Pull master into develop

- DetermineSite.cmake
Per @mdreferee, use a curl command to detect AWS. This might be fragile as CMake does not provide `CURL_EXECUTABLE`
> Add ability to detect AWS

- DetermineSite.cmake
- osx_extras.cmake
> Merge Develop into Main

- CHANGELOG.md
Keep `develop` in line with `main`
> Pull CHANGELOG update from main into develop

- .circleci/config.yml
Pull the CircleCI changes into main
> Merge Develop into Main [skip ci]

- esma_generate_automatic_code.cmake
A draft PR to hold this. Based on work  by @tclune and myself in re https://github.com/GEOS-ESM/GEOSchem_GridComp/issues/108
> Tweaks to ACG macro for StratChem issue

- .circleci/config.yml
- .github/workflows/changelog-enforcer.yml
- CHANGELOG.md
- esma_generate_automatic_code.cmake
This pulls the ACG update into `main`
> Pull ACG Fix from develop into main for release

- CHANGELOG.md
- GNU.cmake
> Fix GCC 10 Aggressive

- CHANGELOG.md
- GNU.cmake
> Hotfix to develop

- DetermineSite.cmake
- GNU.cmake
- Intel.cmake
Updates to let GEOS work with Rome.
> Update NAS detection

- CHANGELOG.md
- GNU.cmake
Fixes the GNU Aggressive flags on Graviton2
> Fix GNU Aggressive on Graviton2

- CHANGELOG.md
- FindBaselibs.cmake
Add option to skip pflogger library if BUILD_WITH_PFLOGGER is OFF
> add option to BUILD_WITH_PFLOGGER

- CHANGELOG.md
- UseF2Py.cmake
- UseF2Py2.cmake
- UseF2Py3.cmake
Found a bug with double precision and GNU
> Fix double precision F2PY handling

- .circleci/config.yml
- CHANGELOG.md
- FindBaselibs.cmake
- UseF2Py.cmake
- UseF2Py2.cmake
- UseF2Py3.cmake
- esma.cmake
This PR enables GFE namespace.
Using this as a first test to make sure CI, etc. is okay and annoying/asking @tclune if an issue pops up. If not, a release here and in ESMA_env is needed first along with updates all the way through GEOS. Whee!
> Enable GFE Namespace

- CHANGELOG.md
- osx_extras.cmake
This code is per:
https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#always-full-rpath
> Always use full RPATH on macOS

- CHANGELOG.md
- FindBaselibs.cmake
- osx_extras.cmake
This pulls in the macOS rpath fix.
> Merge Develop into Main for release

- CHANGELOG.md
- esma_add_f2py2_module.cmake
- esma_add_f2py3_module.cmake
- esma_add_f2py_module.cmake
Found during f2py work on AeroApps.
> Fixes for F2PY import tests

- LICENSE.md
I did things in the wrong direction. Bad Matt.
> Merge main into develop

- CHANGELOG.md
- external_libraries/FindBaselibs.cmake
> Make no basedir warning more visible

- CHANGELOG.md
- esma.cmake
This has the Intel flag change from #241 see #240
> Merge develop into main for 3.8.0 release

- CHANGELOG.md
- compiler/flags/NVHPC_Fortran.cmake
This isn't perfect, but it at least allows some CMake to proceed.
> Adds NVHPC Flags file

- .circleci/config.yml
- CHANGELOG.md
- python/f2py/FindF2PY.cmake
- python/f2py/UseF2Py.cmake
- python/f2py/try_f2py_compile.cmake
- python/f2py2/FindF2PY2.cmake
- python/f2py2/UseF2Py2.cmake
- python/f2py2/try_f2py2_compile.cmake
- python/f2py3/FindF2PY3.cmake
- python/f2py3/UseF2Py3.cmake
- python/f2py3/try_f2py3_compile.cmake
This fixes some issues exposed on with f2py on macOS.
> Fix issues with F2PY Compiler handling

- .circleci/config.yml
- CHANGELOG.md
> Fix up CI for Baselibs 7.5.0

- CHANGELOG.md
- compiler/flags/GNU_Fortran.cmake
This PR attempts to support Apple M2 chips by being more "generic" with our processor matching.
> Attempt to support Apple M2

- .circleci/config.yml
- .github/workflows/changelog-enforcer.yml
- CHANGELOG.md
Minor updates before making a release.
> Update changelog enforcer and CI

- CHANGELOG.md
- compiler/esma_compiler.cmake
This PR adds a print of the processor description. This could be useful in situations like #291
> Add print for processor description

- .circleci/config.yml
- CHANGELOG.md
- compiler/flags/IntelLLVM_Fortran.cmake
- compiler/flags/Intel_Fortran.cmake
This PR brings the preliminary ifx support from @dkokron into a release of ESMA_cmake.
> Gitflow: Merge develop into main for release

- CHANGELOG.md
> GitFlow: Merge Develop into main

- CHANGELOG.md
- compiler/flags/Intel_Fortran.cmake
- external_libraries/DetermineSite.cmake
- python/f2py2/FindF2PY2.cmake
This PR has updates needed for running on the Milan processors on SCU17 at NCCS.
Note that currently to run on SCU17, you must build on SCU17 due to OS differences.
> Updates for SCU17

- CHANGELOG.md
- esma_support/esma_fortran_generator_list.cmake
Closes #308 
Per @scivision in #308, we should quote our generator expression arguments. I've been a bit lazy and just forgot to do this. So let's do it!
> Quote generator expression arguments

- CHANGELOG.md
- python/f2py3/UseF2Py3.cmake
Closes #371 
This sort of seems to get things working with meson. It uses the one-step way and as far as I can say it *builds*. Not sure if anything built with it works!
I might need to work with @patricia-nasa and see if we can test this in AeroApps.
> WIP: Fixes for f2py + meson with Python 3.12

- CHANGELOG.md
- python/f2py3/UseF2Py3.cmake
Fixes a bug with the meson detection in f2py3.
> Fix meson/distutils issue

- .github/workflows/changelog-enforcer.yml
- .github/workflows/validate_yaml_files.yml
- .yamllint.yml
- CHANGELOG.md
Adds a YAML linter to this repo
> Add yaml linter

- CHANGELOG.md
- esma_support/esma_add_fortran_submodules.cmake
- esma_support/esma_support.cmake
This adds `esma_add_fortran_submodules()` to the v3 branch
> Add esma_add_fortran_submodules (v3)

- CHANGELOG.md
- esma_support/esma_add_fortran_submodules.cmake
This is #387 but for the v3 branch of ESMA_cmake
> v3: Update the file esma_add_fortran_submodules.cmake

- CHANGELOG.md
- esma_support/esma_add_fortran_submodules.cmake
- Update the file `esma_add_fortran_submodules.cmake` to handle several levels of subdirectories.
- Edit the `CHANGELOG.md` file.
> Update the file esma_add_fortran_submodules.cmake

- .editorconfig
- CHANGELOG.md
- external_libraries/DetermineSite.cmake
- python/f2py2/FindF2PY2.cmake
This PR has updates needed to build with v3.6 on SLES15 at NCCS
> v3.6: Updates needed to run on SLES15 at NCCS

- CHANGELOG.md
- external_libraries/FindJeMalloc.cmake
This PR has adds `FindJeMalloc.cmake` for use with GEOS. This is NOT enabled by default but is being explored in runs of GEOS.
> Add FindJeMalloc.cmake (v3 branch)

- CHANGELOG.md
- external_libraries/DetermineSite.cmake
This PR removes NCCS OS detection.
> v3: Remove NCCS OS detection

- CHANGELOG.md
- external_libraries/DetermineSite.cmake
This PR removes NCCS OS detection for v4
> v4: Remove NCCS OS detection

- CHANGELOG.md
- python/f2py3/UseF2Py3.cmake
This fixes a stupid bug in the f2py3 code.
> v4: Fix f2py3 bug

- .circleci/config.yml
- .github/workflows/enforce-labels.yml
- .github/workflows/spack-ci.yml
- .github/workflows/validate_yaml_files.yml
- .github/workflows/workflow.yml
- CHANGELOG.md
- esma.cmake
- external_libraries/FindBaselibs.cmake
- operating_system/osx_extras.cmake
This PR adds support for libaec instead of szip in GEOSgcm when using Baselibs.
We also backport some updates from v4
> v3: Add libaec support

- .github/workflows/spack-ci.yml
- .github/workflows/validate_yaml_files.yml
- .github/workflows/workflow.yml
- CHANGELOG.md
- external_libraries/FindBaselibs.cmake
This PR adds support for libaec instead of szip in GEOSgcm when using Baselibs.
> v4: Add libaec support

- CHANGELOG.md
- external_libraries/FindISSM.cmake
This PR adds a `FindISSM.cmake` file for use in linking to ISSM.
> v3: Add FindISSM.cmake
