GEOS-ESM/ESMA_cmake

esma.cmake, esma_add_library.cmake
include_directories must be specified differetly for BUILD vs INSTALL.
Further corrections are needed in some components that add_library().
=> Fixing issues with cmake include_directories.

FindGitInfo.cmake, esma.cmake
This is a package found at:
https://github.com/RWTH-HPC/CMake-gitinfo/blob/master/cmake/FindGitInfo.cmake
which seems to do what's needed for the `CVSTAG` business.
It was about the only package I found that could correctly see that
`@MAPL` was on a *different* tag than `GEOSadas`. I'm sure @tclune could
figure this out, but I was in a bit of a rush, so, for now, I "borrow"
from another expert. The code bits used in GEOSdas_App are (based on
examples from above):
```cmake
if(GIT_FOUND)
GIT_WC_INFO(${PROJECT_SOURCE_DIR} Project)
endif()
if (NOT "${Project_WC_LATEST_TAG}" STREQUAL "")
set (GIT_TAG_OR_REV "${Project_WC_LATEST_TAG}")
else ()
set (GIT_TAG_OR_REV "${Project_WC_REVISION_HASH}")
endif ()
configure_file(CVSTAG.in CVSTAG @ONLY)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/CVSTAG …
```
=> Add GitInfo package.

UseF2Py.cmake
In the CVS model, all the F2Py produced so files are executable.
Apparently, shared object libraries can be executed in some
circumstances:
https://unix.stackexchange.com/questions/40587/why-are-shared-libraries-executable
https://unix.stackexchange.com/questions/223385/why-and-how-are-some-shared-libraries-runnable-as-though-they-are-executables
Are these? Probably not, but I'm trying to get everything identical in
case.
=> Make the F2Py so's executable

esma_generate_automatic_code.cmake
The `install/etc` directory was missing some the `HISTORY___.rc` files that are automatically generated in `GOCART`, et al.
Add `install` step here to install the files into `install/etc`
=> Install automatically generated rc files

UseF2Py.cmake
The "USE_MPI" fix for discover isn't good for macOS because things are `.dylib` not `.so`. Also, there might be `.a` in there as well.
=> Use CMake suffix variables

esma.cmake
This is mainly for NAS and machines where all of the LaTeX stack
might not be available. Now we see if all the needed bits of LaTeX are
found and if not, disable it.
The main issue is that UseLatex seems to die even if it doesn't find
LaTeX!
=> Detect LaTeX presence

esma.cmake, esma_add_library.cmake
Note that packages that use this macro will get warning messages until
they update.   But should be strictly backward compatible with zero-diff in
all fixtures.
Note that this change also expands the esma_add_library() macro a bit.  E.g. one can now pass compiler definitions (e.g., -DMAPL_MODE) on the macro via PUBLIC_DEFINITIONS option.
=> Fixes #34 - improved ecbuild consistency.

FindBaselibs.cmake
We don't need gFTL-Shared or fArgParse yet, so make it `QUIET` if they aren't there.
=> Fixes #26. Add QUIET to two find_package

UseF2Py.cmake
In Python 3, the suffix for f2py shared object libraries gets weird.
For example, instead of
```
GFIO_.so
```
you get:
```
GFIO_.cpython-36m-x86_64-linux-gnu.so
```
`UseF2Py.cmake` seems like it should have supported this, but the CMake
was all wonky and a chunk of the code could *never* run. This fixes it.
BUT, to use this code, `F2PY_SUFFIX` should not be set in any
CMakeLists.txt as it will override the defaults.
=> Updates for future Python 3 support

GNU.cmake
This PR adds support for building with GCC 10. The changes are due to two [changes in GCC 10 Fortran](https://gcc.gnu.org/gcc-10/changes.html) support:
* Mismatches between actual and dummy argument lists in a single file are now rejected with an error. Use the new option `-fallow-argument-mismatch` to turn these errors into warnings; this option is implied with `-std=legacy`. `-Wargument-mismatch` has been removed.
* The handling of a BOZ literal constant has been reworked to provide better conformance to the Fortran 2008 and 2018 standards. In these Fortran standards, a BOZ literal constant is a typeless and kindless entity. As a part of the rework, documented and undocumented extensions to the Fortran standard now emit errors during compilation. Some of these extensions are permitted …
=> Adds support for GCC 10. Min version GCC 8.3

CHANGELOG.md, esma_generate_automatic_code.cmake
This allows ESMA_cmake to function with MAPL before and after the
upcoming reorg of MAPL subdirectories.
=> Generalized paths to MAPL utilities.

FindBaselibs.cmake, esma.cmake, esma_create_stub_component.cmake, esma_enable_tests.cmake
Necessary because of existing hardwired paths in
ESMA_cmake.
=> Additional changes to support MAPL reorg.

esma.cmake
@nosolls has found that some OSs still have issues with F2PY in his container work. As in, it thinks it can do it, but doesn't work right and the install step fails.
Until I am able to test these myself, for now we provide an option for users to just bypass f2py use all together. The default remains at `ON` so that on places like discover, it still acts as before.
=> Add USE_F2PY Option

esma.cmake
It is no longer sufficient to define MKL_Fortran on OS X without giving it a value.
=> Hotfix for more recent CMake

osx_extras.cmake
This commit allows for "easy" use of the mom5/mom6 shared libraries when running on macOS. It hard codes in the `install/lib` path into the LC_RPATH in the executable (as visible with `otool -l`). Without this, the LC_RPATH is `@loader_path/../lib` which means if you run the executable in `experiment/scratch/GEOSgcm.x` it is looking for `experiment/lib`.
=> Add RELATIVE_PATHS fix for macOS

DetermineSite.cmake
In testing Ubuntu 20 docker images on CircleCI, my use of `file(DOWNLOAD)` found a laxity in how I called it. This fixes the issue.
=> Fix download for Ubuntu docker images

CHANGELOG.md, esma.cmake
Use `find_program` to help CMake use *our* Python and not system.
=> Fix f2py tests

.circleci/config.yml
Just does a build. I figure an FV3 Standalone run probably isn't necessary as a CMake bug is usually a build-time bug.
=> Add CircleCI build for ESMA_cmake

Intel.cmake
Fixes #125.
As reported by @lizziel, Harvard had some issues with `-check bounds -check uninit`. While we could have gone to `-check bounds,uninit` using `-check all` is probably better. But, GEOS apparently uses many, many temp copies in routine calls, so we also add `noarg_temp_created`:
> [no]arg_temp_created
> Determines whether checking occurs for actual arguments copied into temporary storage before routine calls.
=> Update check flags for Intel Debug

.circleci/config.yml, CHANGELOG.md
Per Docker, soon there will be [limits on unauthenticated pulls](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/). CircleCI recommends using contexts to authenticate. This PR adds the authentication
=> Add Docker authentication for pulls

.github/workflows/changelog-enforcer.yml, CHANGELOG.md
I keep forgetting that we have a `CHANGELOG.md` here. This will prevent that!
=> Add Changelog Enforcer to ESMA_cmake

CHANGELOG.md, FindBaselibs.cmake
This pulls `develop` into `main` for a release. Added the `BUILD_WITH_PFLOGGER` option.
=> Merge Develop into Main

CHANGELOG.md, FindF2PY2.cmake, FindF2PY3.cmake, UseF2Py2.cmake, UseF2Py3.cmake, check_compiler_support/try_f2py2_compile.cmake, check_compiler_support/try_f2py3_compile.cmake, esma.cmake, esma_add_f2py2_module.cmake, esma_add_f2py3_module.cmake, esma_add_f2py_module.cmake, esma_check_python2_module.cmake, esma_check_python3_module.cmake, esma_find_python2_module.cmake, esma_find_python3_module.cmake
This PR essentially adds Python2 and Python3 versions of all the f2py and other Python bits in ESMA_cmake. 
Note that this will require changes for anything that uses the macros. For example, before with, say, GFIO we had:
```cmake
if (F2PY_FOUND)
if (precision STREQUAL "r4")
add_f2py_module(GFIO_ SOURCES GFIO_py.F90
DESTINATION lib/Python
ONLY gfioopen gfiocreate gfiodiminquire gfioinquire
gfiogetvar gfiogetvart gfioputvar gfiogetbegdatetime
gfiointerpxy gfiointerpnn gfiocoordnn gfioclose
)
add_dependencies(GFIO_ ${this})
endif ()
endif ()
```
Now one would do:
```cmake
if (USE_F2PY)
if (precision STREQUAL "r4")
find_package(F2PY2)
if (F2PY2_FOUND)
esma_add_f2py2_module(GFIO_ SOURCES GFIO_py.F90
DESTINATION lib/Python2
ONLY gfioopen gfiocreate gfiodiminquire gfioinquire
gfiogetvar …
```
=> Updates to use Python2 and Python3 at same time

CHANGELOG.md, esma.cmake, esma_add_library.cmake, esma_set_this.cmake
This change allows users to specify specific extra FPP definitions to
a select group of source files.  To use:
```
$cmake .. -DXFLAGS="foo bar=7 DEBUG" -DXFLAGS_SOURCES="<file1> <file2>"
$ make
```
=> Improved fix for #175 - custom FPP defs.

CHANGELOG.md, FindBaselibs.cmake
This PR does a couple things:
- Add ability to detect BASEDIR from the environment.
- Add checks to `FindBaselibs.cmake` to make sure BASEDIR has the right arch (as defined by `uname -s`) as this is still a requirement for GEOS run scripts. The code will also try to make a valid BASEDIR. That is, if you pass in `/path/to/baselibs`, but it sees a `/path/to/baselibs/arch/lib` exists, it will allow that and try to use it.
=> Add ability to detect BASEDIR from environment

CHANGELOG.md, FindBaselibs.cmake
This PR updates ESMA_cmake to use `libesmf.dylib` on macOS. This is now possible with [Baselibs v6.2.5](https://github.com/GEOS-ESM/ESMA-Baselibs/releases/tag/v6.2.5). Linux is not affected by this PR. 
I also added a little check so that it makes sure `libesmf.so` or `libesmf.dylib` exists.
=> Use ESMF dylib on macOS

CHANGELOG.md, UseF2Py.cmake, UseF2Py2.cmake, UseF2Py3.cmake
In working with @patricia-nasa and others doing a lot of `f2py` work, they often need to remove the `&> /dev/null` from the macros to let them see *why* f2py is failing.
So with this PR, if you build with `Debug` `CMAKE_BUILD_TYPE` then we make `f2py` noisy again. But we only do this if you are doing `Debug` as f2py is very noisy even when things are working!
Making draft for now so I can test on discover with a GEOS build. I'll then rope in @tclune to approve.
=> Make f2py noisier if building Debug

CHANGELOG.md, esma_cpack.cmake
This adds some CPack configuration to ESMA_cmake that allows one to run `make package_source` or `make dist` in a build directory and the code will be tarred up for the user.
Note that due to ecbuild oddities, the `include(esma_cpack)` needs to be done *after* the call to `ecbuild_install_project` so that our CPack wins over ecbuild's. Thus we can't just have this include in the `esma.cmake` file. Dang.
=> Add esma_cpack

CHANGELOG.md, esma_create_stub_component.cmake, esma_generate_automatic_code.cmake
This might be a "leave well enough alone" change, but when I was looking at some code with @Gvilla1000-nasa, I saw some things in ESMA_cmake that looked odd. Namely mentions of "MAPL_Base" which hasn't been around awhile. The `mapl_acg.pl` and `mapl_stub.pl` scripts now live in `@MAPL/Apps` so I've changed two scripts here to reflect that.
=> Clean up MAPL references

CHANGELOG.md, FindBaselibs.cmake
Recently, Alexander Gruber (@alexgruber, I think), encountered an issue with GEOSldas when linking to ESMF:
```
[ 61%] Linking Fortran executable ../../../../bin/cub2latlon.x
/staging/leuven/stg_00024/GEOSldas_libraries/ESMA-Baselibs-6.2.4/src/Linux/lib/libesmf.so: error: undefined reference to 'shm_open'
/staging/leuven/stg_00024/GEOSldas_libraries/ESMA-Baselibs-6.2.4/src/Linux/lib/libesmf.so: error: undefined reference to 'shm_unlink'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/cub2latlon.x] Error 1
make[1]: *** [src/Shared/@MAPL/base/CMakeFiles/cub2latlon.x.dir/all] Error 2
```
This is the first time I've seen it. I *think* the fix is to add `librt` and `libdl` to the `ESMF_LIBRARIES` for GEOS. 
This PR is where I'm tracking this, depending on how it works for …
=> Add librt and libdl to the ESMF libraries

CHANGELOG.md, external_libraries/FindBaselibs.cmake
Closes #216 
If you run CMake from a terminal that does have BASEDIR defined, but then move to a terminal that doesn't, subsequent `cmake` will fail. This PR changes the order of some statements so that when a good BASEDIR is found, it is then cached.
=> Fixes #216. Cache BASEDIR

CHANGELOG.md, esma.cmake, esma_support/esma_support.cmake
The refactoring done in #207 had a mistake that broke `make tests` in MAPL. This fixes that issue.
Essentially, this:
```cmake
include (esma_enable_tests)
```
was never being called before.
=> Fix tests target

CHANGELOG.md, compiler/flags/GNU_Fortran.cmake, compiler/flags/Generic_Fortran.cmake, compiler/flags/Intel_Fortran.cmake, compiler/flags/NAG_Fortran.cmake, compiler/flags/PGI_Fortran.cmake
It turns out CICE4 cannot run with the new all-vectorized flags (see https://github.com/GEOS-ESM/GEOSgcm/issues/336). In order to use the old flags, this creates a new set of "NoVect" variables that are the old `Release` flags.
=> Restore the old Intel non-vectorized Release flags as new NoVect variable

.circleci/config.yml, CHANGELOG.md, external_libraries/FindBaselibs.cmake
Closes #233 
This removes `find_package()` calls for GFE libraries in `FindBaselibs.cmake`.
Keeping draft for now as this will need an update for MAPL as well (so we can find the packages)
=> Remove find_package from FindBaselibs.cmake

CHANGELOG.md, esma.cmake
Closes #236 
This PR moves the call for `FindBaselibs.cmake` up in the order of calls. This sets `CMAKE_PREFIX_PATH` earlier.
Blocking until I can do more tests to make sure.
=> Fixes #236. Move FindBaselibs up in order

CHANGELOG.md, esma.cmake
Move a few more finds in `esma.cmake` up in the order. f2py calls were having issues with pthread and I think it was due to an order-of-operations.
Well, maybe. I dunno, this worked for me.
=> Merge Develop into Main for Release

CHANGELOG.md, external_libraries/FindGitInfo.cmake
There is a chance you could be in a git-stripped tarball. This change means the CMake step will not error out. That case is then covered upstream in the place that uses this macro.
Note: We only use the `_WC_LATEST_TAG` bit of this code, so that's what I 'protect' by setting it to a blank string.
=> Fix git-stripped case

.circleci/config.yml, CHANGELOG.md
This PR compresses the CircleCI artifacts since CircleCI will soon charge for storage over a limit:
https://circleci.com/docs/2.0/persist-data/#storage
This is trivially zero-diff to the model as it only affects CI
=> Compress CircleCI Artifacts

CHANGELOG.md, external_libraries/FindESMF.cmake
This PR adds the NOAA-EMC `FindESMF.cmake` package for use with Spack-based GEOS.
=> Add FindESMF.cmake from NOAA-EMC

CHANGELOG.md, external_libraries/FindBaselibs.cmake, external_libraries/FindESMF.cmake
This PR moves ESMA_cmake to use `FindESMF.cmake` when running with Baselibs. This was motivated by @bena-nasa finding that GEOS did not like to build with recent ESMF where PIO has changed internally and now seems to be a required link with how we build ESMF (`ESMF_PIO=internal`). @rsdunlapiv has said that supporting PIO on places like discover would be good. 
Our current way of linking to ESMF-in-Baselibs is a bit _ad hoc_ and more based on historical ways of how we used to build in GNU days. It was...horrible and there are better ways.
So, now, we used `FindESMF.cmake` in conjunction with `esmf.mk` to get ESMF. Also, we alter the `FindESMF.cmake` in ESMA_cmake to prefer the shared object library over the static as this is how we are currently doing it.
NOTE: I'm keeping this draft until …
=> Use FindESMF.cmake with Baselibs

CHANGELOG.md, external_libraries/FindBaselibs.cmake
Testing building ADAS-only directories of GMAO_Shared (https://github.com/GEOS-ESM/GMAO_Shared/pull/262) showed that we need to tell CMake that ESMF depends on MPI when built in Baselibs.
=> Add dependency to MPI for Baselibs ESMF

CHANGELOG.md, compiler/flags/GNU_Fortran.cmake, compiler/flags/Intel_Fortran.cmake
This is a tracking branch for M1 support of GEOS. 
Current testing (with generous help from @iains), see:
https://github.com/GEOS-ESM/GEOSgcm/issues/417
has shown that GEOS seems to not be happy with `-march=native` and whatever other flags we do for Aggressive. So, for now, we just make our Aggressive build match that of Release. Testing shows the Release flags seem to be pretty darn good so it's not like we are missing much.
=> Changes needed to run GEOS on M1

.circleci/config.yml, CHANGELOG.md, esma_cpack.cmake
This PR attempts to fix a weird CPack issue reported by @sdrabenh and @Jcampbell-8. I think the issue is that an editor has made a tempfile in the model that is seen by CMake at CMake time. But by the time CPack runs at the end, the tempfile is gone causing a fault.
So, we add various tempfile patterns to `CPACK_SOURCE_IGNORE_FILES` to fix this.
=> Add more ignores to CPack

CHANGELOG.md, esma.cmake, esma_support/esma_check_install_prefix.cmake
This PR adds a check in `esma.cmake` to make sure the `CMAKE_INSTALL_PREFIX` provided is writable. This is pretty hard to trigger for most people, but belt-and-suspenders is never a bad thing.
Inspired by @scivision in this post: https://www.scivision.dev/cmake-test-path-writable/ . His version is more elegant, but I was trying out GitHub Copilot and it suggested this. The AI code seems...reasonable.
=> Check to make sure install dir is writable

CHANGELOG.md, compiler/flags/GNU_Fortran.cmake
This PR adds `-save-temps` to the GNU debugging flags. Useful and matches what is done for Intel.
=> Add save-temps for GNU Debug

CHANGELOG.md, compiler/flags/Intel_Fortran.cmake
Closes #296 
This PR adds extra flags to Intel Fortran Debug builds to make them stricter:
- `-stand f18` to enable Fortran 2018 Standard compliance
- `-diag-error 6188` to cause if(integer) to fail
- `-diag-error 6192` to cause logical set to integer to fail
- `-diag-disable 5268` to suppress warning for long source lines (which our macros often make)
=> Update Intel Fortran Debugging flags

.circleci/config.yml, CHANGELOG.md, compiler/flags/IntelLLVM_Fortran.cmake
Closes #299 
Per @dkokron in #299, `ifx` does not support `-fp-model source` and per [Intel's docs](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/compiler-reference/compiler-options/floating-point-options/fp-model-fp.html) it doesn't support `-fp-model consistent`. So this PR adds an `IntelLLVM_Fortran.cmake` file that is just a copy of `Intel_LLVM.cmake` with these options blanked.
I commented out the old flags because, well, those two flags are sort of important for GEOS chip-change reproducibility and I hope they come back...
=> Updates for ifx support

.github/workflows/enforce-labels.yml, CHANGELOG.md
This PR uses the new ability of v3 of our label enforcer to provide for a custom message upon enforcer failure.
=> Add custom messages to label enforcers

CHANGELOG.md, external_libraries/FindBaselibs.cmake
This is a pretty hacky way to build code in GEOS that uses the `HDF5::HDF5` target and Baselibs. This is needed because Baselibs doesn't build HDF5 with CMake so we don't get the targets automatically.
When we move to Spack, this becomes moot.
=> Add HDF5::HDF5 alias for Baselibs builds

CHANGELOG.md, external_libraries/DetermineSite.cmake
This is an attempt to add detection of Azure machines in ESMA_cmake. It's a bit hacky[^1], but it does seem work on Azure, but I need to make sure I didn't just break NCCS, etc. So I'll keep draft for now.
Also, I don't have access to GCE at the moment but I'm guessing it'll be something similar following:
https://cloud.google.com/compute/docs/instances/detect-compute-engine
[^1]: I'm sure at some point I'll find the post on the @scivision blog that has nice elegant code for this sort of thing 😄
=> Add detection of Azure

CHANGELOG.md, external_libraries/DetermineSite.cmake
Because you can only run on Romes at NAS if you build on Romes at NAS (because of different OSs), this PR is an attempt to detect when built on Rome for use in other bits of GEOS.
=> Add Rome detection at NAS

CHANGELOG.md, external_libraries/DetermineSite.cmake
With NAS moving all of its systems to TOSS4, the "detect if Rome" bits of ESMA_cmake can be removed. 
This PR is in concert with https://github.com/GEOS-ESM/GEOSgcm_App/pull/460
=> Remove BUILT_ON_ROME detection at NAS

CHANGELOG.md, compiler/flags/Intel_Fortran.cmake
This PR adds a `QUIET_DEBUG` option for Intel Fortran to suppress a lot of the output from compilation.
This will mainly be used in CI cases where output it too voluminous and breaks things.
=> Add QUIET_DEBUG option

CHANGELOG.md, compiler/flags/Intel_Fortran.cmake
This pulls in a fix from @tclune for building on macOS under Rosetta.
=> Fixes for Intel Rosetta under Clang 15

CHANGELOG.md, compiler/esma_compiler.cmake
Testing with Intel Fortran Classic 2021.10 found that we need a new flag `-Wno-implicit-int` when using `icx` because the Intel oneAPI 2023.2 module at NCCS uses `icx` as the C compiler.
=> Add needed flag for icx builds

CHANGELOG.md, external_libraries/FindESMF.cmake
Testing of Spack and GEOS (in collaboration with @climbfuji) found that GEOSgcm itself needs `FindESMF.cmake` when building with mainline Spack. GEOS-Baselibs builds do not need this because ESMA_cmake "knows" where the module is in a Baselibs install of ESMF. But with spack, this is not known. This is perhaps not the most elegant solution but it works.
The ESMF spack package does [install a `cmake/` directory](https://github.com/spack/spack/blob/edc8a5f24964daa404a49edfd5d539b1ca808ae0/var/spack/repos/builtin/packages/esmf/package.py#L406-L408) with the file:
```python
@run_after("install")
def post_install(self):
install_tree("cmake", self.prefix.cmake)
```
but as far as I can see, that path is not exposed via any environment variable in the esmf modulefile produced by spack. …
=> Add FindESMF.cmake for Spack builds

CHANGELOG.md, external_libraries/FindBaselibs.cmake
This PR adds an `ESMF::ESMF` alias to builds using Baselibs. This is needed for UFS builds of MAPL/GOCART, see https://github.com/GEOS-ESM/MAPL/issues/2569
This also means that this upcoming version of ESMA_cmake (v3.39.0) will be required by MAPL 2.44 when all changes are in.
=> Add ESMF::ESMF Alias

CHANGELOG.md, esma.cmake, external_libraries/DetermineMPIStack.cmake
This PR uses CMake to determine the MPI stack for GEOS. It provides two new variables:
- `MPI_STACK`: The detected MPI stack. The possible variables set are:
- `intelmpi`
- `openmpi`
- `mpt`
- `mpich`
- `mvapich`
A user can also override this with `-DMPI_STACK=openmpi` say and the whole autodetection will be skipped.
- `MPI_STACK_VERSION`
- NOTE: This is not the version of MPI standard the stack supports, but the version of the stack itself.
For the MPI Standard supported use `MPI_C_VERSION` and `MPI_Fortran_VERSION` provided by `FindMPI` module.
=> Use CMake to determine MPI Stack

CHANGELOG.md, compiler/flags/NAG_Fortran.cmake
This adds the `-quiet` flag for NAG:
```
-quiet    Suppress the compiler banner and the summary line, so that only diagnostic messages will appear.
```
So this:
```
❯ mpifort -o helloWorld.mpi3.exe helloWorld.mpi3.F90
NAG Fortran Compiler Release 7.1(Hanzomon) Build 7143
[NAG Fortran Compiler normal termination]
```
becomes:
```
❯ mpifort -quiet -o helloWorld.mpi3.exe helloWorld.mpi3.F90
```
which is nice.
=> Add quiet flag for NAG

CHANGELOG.md, compiler/flags/Intel_Fortran.cmake
Testing by @tclune found a weird failure in pfio unit tests in MAPL (see https://github.com/GEOS-ESM/MAPL/issues/2641). Further testing found the bug could be triggered in a standalong netCDF-Fortran code. 
Eventually, it was found that setting either `-init=snan,arrays` or `-fpe0` caused the `nf90_create` call to crash. 
This PR removes those flags if the `ifort` version is 2021.10 or higher.
NOTE: I have no idea if this is zero-diff or non-zero-diff. I'm not sure if `-fpe0` causes a change...
=> Fix Intel Debug flags for Intel ifort 2021.10+

CHANGELOG.md, compiler/flags/Intel_Fortran.cmake
This PR undoes #364. The issue detailed there seems to have been due to the use of HDF5 in Baselibs 7.18 and 7.19. We don't know why, but HDF5 1.14 was causing `nf90_create` issues in MAPL with Intel and NAG.
So we reverted back to HDF5 1.10 and so #364 is unineeded
=> Undo #364. Issue was due to HDF5 1.14

CHANGELOG.md, esma_support/esma_enable_tests.cmake
This PR changes the usual `make tests` command we often use in GEOS to run only those tests labeled with `ESSENTIAL`. To run all tests, use `make tests-all`.
This will require a PR in MAPL as well to "work" in that, if you have ESMA_cmake v3.43 but not the concomitant PR in MAPL, you'll run...nothing since nothing will have the `ESSENTIAL` label.
=> Run essential tests with make tests

CHANGELOG.md, external_libraries/DetermineSite.cmake
As found by @weiyuan-jiang I was lazy and if you were at NCCS and did not build on SLES15, `BUILT_ON_SLES15` was not `FALSE` but empty. This is less than ideal just in case blank is a truthy value.
Note: This depends on fixing code in GEOS_Util (see https://github.com/GEOS-ESM/GEOS_Util/pull/66)
=> Set BUILT_ON_SLES15 to FALSE if not

CHANGELOG.md, compiler/flags/Intel_Fortran.cmake
This PR suppresses the:
```
ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.
```
warning from ifort about ifort's deprecation. This happens with *every* call to ifort so it gets...annoying.
=> Suppress ifort deprecation warning

CHANGELOG.md, external_libraries/FindBaselibs.cmake, external_libraries/FindESMF.cmake
This updates `FindESMF.cmake` to make `ESMF::ESMF` the main target and `ESMF` an alias.
Related: https://github.com/GEOS-ESM/MAPL/pull/2682
=> Update FindESMF.cmake to make ESMF::ESMF main target

CHANGELOG.md, compiler/flags/GNU_Fortran.cmake
Closes #360 
This PR adds support for Hygon processors with GCC. Tests by @TianYangMY in https://github.com/geoschem/GCHP/issues/391 showed that GCC 10 reported `nocona` as its arch. Seems a bit old (Pentium 4!) but should be safe. I'll keep this draft until testing has occurred.
=> Add support for Hygon with GCC

CHANGELOG.md, python/f2py3/UseF2Py3.cmake
This fixes an issue between f2py3 and meson and python 3.12 found by @patricia-nasa.
NOTE: Requires a fix to  f2py  that is not yet released. You can see the change in the `numpy`  repo at https://github.com/numpy/numpy/pull/26659
This fix has been applied to GEOSpyD 2.44.0-0 by hand my @JulesKouatchou and myself
=> Fixes for Python 3.12, meson, and f2py (v3 branch)

CHANGELOG.md, python/f2py3/UseF2Py3.cmake
This fixes an issue between f2py3 and meson and python 3.12 found by @patricia-nasa.
NOTE: Requires a fix to  f2py  that is not yet released. You can see the change in the `numpy`  repo at https://github.com/numpy/numpy/pull/26659
This fix has been applied to GEOSpyD 2.44.0-0 by hand my @JulesKouatchou and myself
=> Fixes for Python 3.12, meson, and f2py

CHANGELOG.md, esma_support/esma_add_fortran_submodules.cmake, esma_support/esma_support.cmake
- Add a new function to handle possible  conflicts when submodule files have the same name.
=> New function

CHANGELOG.md, esma.cmake, external_libraries/FindBaselibs.cmake
This moves the `find_package(MPI)` call out of `FindBaselibs` which is now a dumb thing to do for Spack work.
Indeed, I think this is this issue for the insanity I've had to add to the MAPL spack package. Apologies to @climbfuji, @AlexanderRichert-NOAA, and potentially @Hang-Lei-NOAA.
=> v3: Move detection of MPI out of FindBaselibs

CHANGELOG.md, esma.cmake, external_libraries/FindBaselibs.cmake
This moves the `find_package(MPI)` call out of `FindBaselibs` which is now a dumb thing to do for Spack work.
Indeed, I think this is this issue for the insanity I've had to add to the MAPL spack package. Apologies to @climbfuji, @AlexanderRichert-NOAA, and potentially @Hang-Lei-NOAA.
=> Move detection of MPI out of FindBaselibs

CHANGELOG.md, esma_support/esma_add_fortran_submodules.cmake
Edited the file `esma_add_fortran_submodules.cmake` to add the `SMOD` word in the target submodule file name. Now the submodule file name (`file.F90`) will be renamed (for compilation purpose only) `moduleName_SMOD_file.F90` instead of `moduleName_file.F90`.
Based on #393 from @JulesKouatchou
=> v3: Add the SMOD word in the target submodule file name

CHANGELOG.md, esma_support/esma_add_fortran_submodules.cmake
Edited the file `esma_add_fortran_submodules.cmake` to add the `SMOD` word in the target submodule file name. Now the submodule file name (`file.F90`) will be renamed (for compilation purpose only) `moduleName_SMOD_file.F90` instead of `moduleName_file.F90`.
=> Add the SMOD word in the target submodule file name.

CHANGELOG.md, compiler/flags/NAG_Fortran.cmake, esma.cmake
This adds a workaround for a bug between NAG, OpenMP, and CMake.
See https://gitlab.kitware.com/cmake/cmake/-/issues/21280 for more info.
=> Workaround for OpenMP + NAG + CMake (v3)

CHANGELOG.md, compiler/flags/NAG_Fortran.cmake, esma.cmake
This adds a workaround for a bug between NAG, OpenMP, and CMake.
See https://gitlab.kitware.com/cmake/cmake/-/issues/21280 for more info.
=> Workaround for OpenMP + NAG + CMake

CHANGELOG.md, compiler/flags/LLVMFlang_Fortran.cmake
This PR adds preliminary support for LLVM Flang. 
NOTE: This is *very* basic and probably does not work completely yet! Based on the GNU flag file with a lot of deletions and commenting.
=> v3: Add preliminary Flang support

CHANGELOG.md, compiler/flags/LLVMFlang_Fortran.cmake
This PR adds preliminary support for LLVM Flang.
NOTE: This is _very_ basic and probably does not work completely yet! Based on the GNU flag file with a lot of deletions and commenting.
=> Add preliminary Flang support

.circleci/config.yml, CHANGELOG.md, esma_support/esma_create_stub_component.cmake, esma_support/esma_generate_automatic_code.cmake
It has been requested by some of the spack-stack folks (e.g., @climbfuji) that GEOSgcm when built with Spack should be able to use MAPL as a library rather than as a component built in.
I believe this is all that is necessary. We just need to tell CMake where `mapl_stub.pl` is. Because MAPL is built under ecbuild, that means it has a variable called `MAPL_BASE_DIR`[^1] that points to where MAPL is, e.g., in spack, where spack installed it.
[^1]: This is not great for MAPL since MAPL_Base is a thing for us, but, well, that's what ecbuild does.
=> v4: Support for MAPL-as-library

CHANGELOG.md, esma.cmake, esma_support/esma_mepo_status.cmake, esma_support/esma_support.cmake
This PR adds a new `esma_capture_mepo_status` function (in `esma_support/esma_mepo_status.cmake`) to capture the output of `mepo status --hashes` when `mepo` was used to clone the fixture. It will output this into a file `MEPO_STATUS.rc` which is installed to `${CMAKE_INSTALL_PREFIX}/etc` and can be used to help determine the exact state of the fixture at build time.
This was suggested/inspired by @viral211
=> v3: Add output of mepo status

.circleci/config.yml, CHANGELOG.md, esma.cmake, esma_support/esma_mepo_status.cmake, esma_support/esma_support.cmake
This PR adds a new `esma_capture_mepo_status` function (in `esma_support/esma_mepo_status.cmake`) to capture the output of `mepo status --hashes` when `mepo` was used to clone the fixture. It will output this into a file `MEPO_STATUS.rc` which is installed to `${CMAKE_INSTALL_PREFIX}/etc` and can be used to help determine the exact state of the fixture at build time.
This was suggested/inspired by @viral211 
Closes #407
=> v4: Add output of mepo status

CHANGELOG.md, esma.cmake
There are cases where we do not require MPI. In such cases, we cannot run the `DetermineMPIStack` code.
=> v3: Do not determine MPI stack without MPI found

CHANGELOG.md, esma.cmake
There are cases where we do not require MPI. In such cases, we cannot run the `DetermineMPIStack` code.
=> v4: Do not determine MPI stack without MPI found

CHANGELOG.md, compiler/checks/check_fortran_support.cmake, esma_support/esma_mepo_status.cmake, python/esma_python.cmake, python/f2py/FindF2PY.cmake, python/f2py/UseF2Py.cmake, python/f2py/esma_add_f2py_module.cmake, python/f2py/try_f2py_compile.cmake, python/f2py3/FindF2PY3.cmake, python/f2py3/UseF2Py3.cmake, python/f2py3/esma_add_f2py3_module.cmake, python/f2py3/try_f2py3_compile.cmake
Using CMake + f2py + Meson seems to need a new CMake policy set. See:
https://github.com/mesonbuild/meson/issues/13882
=> v3: Updates for meson-f2py support

CHANGELOG.md, compiler/checks/check_fortran_support.cmake, esma_support/esma_mepo_status.cmake, python/esma_python.cmake, python/f2py/FindF2PY.cmake, python/f2py/UseF2Py.cmake, python/f2py/esma_add_f2py_module.cmake, python/f2py/try_f2py_compile.cmake, python/f2py3/FindF2PY3.cmake, python/f2py3/UseF2Py3.cmake, python/f2py3/esma_add_f2py3_module.cmake, python/f2py3/try_f2py3_compile.cmake
Using CMake + f2py + Meson seems to need a new CMake policy set. See:
https://github.com/mesonbuild/meson/issues/13882
=> v4: Updates for meson-f2py support

CHANGELOG.md, external_libraries/DetermineMPIStack.cmake
This PR fixes an issue when running CMake more than once on the same code. The second+ times through, `MPI_STACK` was already set, so therefore you got a warning saying "MPI_STACK was set by user..."
=> v3: Fix multiple MPI_STACK sets

CHANGELOG.md, python/esma_find_python3_module.cmake, python/esma_python.cmake
Tests at NAS have shown that using the `VERSION` find strategy for Python was causing an issue because there is a `/usr/bin/python3.12` that is on the system `PATH` but it is "basic" and doesn't have `f2py` so our `f2py` bits were failing. 
Using `LOCATION` tells it to use the Python we want (e.g., GEOSpyD)
=> v3: Use LOCATION Python FIND_STRATEGY

CHANGELOG.md, python/esma_find_python3_module.cmake, python/esma_python.cmake
Tests at NAS have shown that using the `VERSION` find strategy for Python was causing an issue because there is a `/usr/bin/python3.12` that is on the system `PATH` but it is "basic" and doesn't have `f2py` so our `f2py` bits were failing. 
Using `LOCATION` tells it to use the Python we want (e.g., GEOSpyD)
=> v4: Use LOCATION Python FIND_STRATEGY

CHANGELOG.md, compiler/flags/Intel_Fortran.cmake
This PR updates the Intel Fortran flags as tested by @wmputman
These should go along with two other PRs:
* GEOSradiation_GridComp: https://github.com/GEOS-ESM/GEOSradiation_GridComp/pull/63
* fvdycore: https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/109
=> v12: Updated Intel Fortran flags

CHANGELOG.md, external_libraries/FindBaselibs.cmake, python/esma_python.cmake, python/f2py/FindF2PY.cmake, python/f2py/try_f2py_compile.cmake, python/f2py2/FindF2PY2.cmake, python/f2py3/FindF2PY3.cmake, python/f2py3/try_f2py3_compile.cmake
This PR to v3 is an attempt to let f2py work in odd scenarios where perhaps more than one Python stack is in the PATH. In some cases, this is expected (Spack) but in other cases, it is an unsupported way forward (two different Miniforge stacks of different Python vintage).
First, we look for bare `f2py` first as systems like Spack only install that.
Second, we look to see if the Python executable is the same path as the f2py found. If not, we add a `WARNING` to the CMake output. We cannot `FATAL_ERROR` because of things like Spack. 
This is about as good as we can do.
We also add an ugly hack for f2py on macOS with AppleClang because meson and CC and I don't know anymore.
=> v3: Fixes to allow for odd Python setups and f2py

CHANGELOG.md, external_libraries/FindBaselibs.cmake, python/esma_python.cmake, python/f2py/FindF2PY.cmake, python/f2py/try_f2py_compile.cmake, python/f2py2/FindF2PY2.cmake, python/f2py3/FindF2PY3.cmake, python/f2py3/try_f2py3_compile.cmake
This PR to v4 is an attempt to let f2py work in odd scenarios where perhaps more than one Python stack is in the PATH. In some cases, this is expected (Spack) but in other cases, it is an unsupported way forward (two different Miniforge stacks of different Python vintage).
First, we look for bare `f2py` first as systems like Spack only install that.
Second, we look to see if the Python executable is the same path as the f2py found. If not, we add a `WARNING` to the CMake output. We cannot `FATAL_ERROR` because of things like Spack. 
This is about as good as we can do.
We also add an ugly hack for f2py on macOS with AppleClang because meson and CC and I don't know anymore.
=> v4: Fixes to allow for odd Python setups and f2py

CHANGELOG.md, compiler/flags/IntelLLVM_Fortran.cmake
This pull request updates the Intel LLVM Fortran flags to use `-march=x86-64-v3` instead of `-march=core-avx2` across various configurations. This change ensures better compatibility and performance consistency across different processor types.
* [`compiler/flags/IntelLLVM_Fortran.cmake`](diffhunk://#diff-a7f6a702d45622d2a2a32bbc05824ad0e356eb6173e34e7061df7ef43d8388feL66-R77): Replaced `-march=core-avx2` with `-march=x86-64-v3` for AMD EPYC, Hygon, and Intel processors. Updated fallback flag for unknown processor types to `-march=x86-64`.
* [`compiler/flags/IntelLLVM_Fortran.cmake`](diffhunk://#diff-a7f6a702d45622d2a2a32bbc05824ad0e356eb6173e34e7061df7ef43d8388feL111-R106): Updated `GEOS_Fortran_Vect_Flags` to use `MARCH_FLAG` instead of `COREAVX2_FLAG`.
* …
=> v3: Update ifx flags for avx2

CHANGELOG.md, compiler/flags/GNU_Fortran.cmake
Current we emit warnings about using `-fallow-argument-mismatch` and `-fallow-invalid-boz` with GCC 10+ but, well, the code hasn't been changed and probably never will be. Indeed, many packages in Spack, etc do this by default as well.
So, we change the warnings to `STATUS` messages for cleanliness.
=> v3: Change GCC10+ warnings to status messages

.circleci/config.yml, CHANGELOG.md, compiler/flags/GNU_Fortran.cmake
Current we emit warnings about using `-fallow-argument-mismatch` and `-fallow-invalid-boz` with GCC 10+ but, well, the code hasn't been changed and probably never will be. Indeed, many packages in Spack, etc do this by default as well.
So, we change the warnings to `STATUS` messages for cleanliness.
=> v4: Change GCC10+ warnings to status messages

CHANGELOG.md, python/f2py3/UseF2Py3.cmake
This fixes a stupid bug in the f2py3 code.
=> v3: Fix f2py3 bug

CHANGELOG.md, compiler/flags/GNU_Fortran.cmake, compiler/flags/IntelLLVM_Fortran.cmake, compiler/flags/Intel_Fortran.cmake
Closes #438 
This PR removes the addition of `-Wl,-ld_classic` on macOS if running XCode 16.3 (or higher). It seems to no longer be needed and indeed causes crashes if included.
=> v3: Fixes for XCode 16.3

CHANGELOG.md, compiler/flags/GNU_Fortran.cmake, compiler/flags/IntelLLVM_Fortran.cmake, compiler/flags/Intel_Fortran.cmake
Closes #438 
This PR removes the addition of `-Wl,-ld_classic` on macOS if running XCode 16.3 (or higher). It seems to no longer be needed and indeed causes crashes if included.
=> v4: Fixes for XCode 16.3

CHANGELOG.md, esma_support/esma_mepo_status.cmake, python/.gitignore, python/f2py/esma_add_f2py_module.cmake, python/f2py3/esma_add_f2py3_module.cmake
This PR has fixes for MPT and meson. It was found that we now need to do `LD_PRELOAD=/path/to/mpt/libmpi.so` when running our `python3 -c 'import f2pyso_'` tests. 
We also set the `mepo status` bit to timeout after 60 seconds.
=> v3: Fixes for MPT and meson

CHANGELOG.md, esma_support/esma_mepo_status.cmake, python/.gitignore, python/f2py/esma_add_f2py_module.cmake, python/f2py3/esma_add_f2py3_module.cmake
This PR has fixes for MPT and meson. It was found that we now need to do `LD_PRELOAD=/path/to/mpt/libmpi.so` when running our `python3 -c 'import f2pyso_'` tests. 
We also set the `mepo status` bit to timeout after 60 seconds.
=> v4: Fixes for MPT and meson

CHANGELOG.md, compiler/esma_compiler.cmake
This PR adds some enforcement to make sure users only ask for our allowed `CMAKE_BUILD_TYPE` variants.
=> v11: Enforce allowed CMAKE_BUILD_TYPE

CHANGELOG.md, compiler/esma_compiler.cmake
This caches the `proc_description` variable for use in https://github.com/GEOS-ESM/GEOSgcm/pull/930
=> v3: Cache proc_description variable

CHANGELOG.md, python/f2py/try_f2py_compile.cmake, python/f2py3/try_f2py3_compile.cmake
This PR fixes an issue found on a machine where `TMPDIR` was pointing to a `noexec` directory. This was causing our f2py tests to fail.
=> v3: Fix f2py TMPDIR issue

CHANGELOG.md, python/f2py/try_f2py_compile.cmake, python/f2py3/try_f2py3_compile.cmake
This PR fixes an issue found on a machine where `TMPDIR` was pointing to a `noexec` directory. This was causing our f2py tests to fail.
=> v4: Fix f2py TMPDIR issue

CHANGELOG.md, external_libraries/check_fms1_io_support.cmake
This PR fixes an issue with the FMS1 I/O test from #462 which didn't handle the `FV_PRECISION=R8` case correctly.
=> v4: Fixes for FV_PRECISION handling

CHANGELOG.md, compiler/flags/IntelLLVM_Fortran.cmake, compiler/flags/Intel_Fortran.cmake
As found by @wmputman, we were using `${FPE1}` for ifort without defining it. oops.
=> Fix missing FPE1 in Intel flags

CHANGELOG.md, compiler/esma_compiler.cmake, compiler/flags/GNU_Fortran.cmake, compiler/flags/Generic_Fortran.cmake, compiler/flags/IntelLLVM_Fortran.cmake, compiler/flags/Intel_Fortran.cmake, compiler/flags/LLVMFlang_Fortran.cmake, compiler/flags/NAG_Fortran.cmake, compiler/flags/NVHPC_Fortran.cmake
There are new VectTrap flags from @wmputman that are used with ifort. We also add stubs for all the other compilers.
The Intel Fortran flags did change and are most likely non-zero-diff as well (came in with other Physics changes)
=> v4: Add new VectTrap flags (only tested on Intel)
